# DigitalOcean App Platform Configuration
# EchoTune AI - AI-Powered Music Discovery Platform

name: echotune-ai

services:
- name: web
  environment_slug: node-js
  github:
    repo: dzp5103/Spotify-echo
    branch: main
    deploy_on_push: true
  
  # Build and run configuration
  build_command: npm ci --only=production
  run_command: npm start
  
  # HTTP configuration
  http_port: 3000
  
  # Resource allocation for cost optimization
  instance_count: 1
  instance_size_slug: basic-xxs
  
  # Environment variables
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: DEFAULT_LLM_PROVIDER
    value: mock
  - key: HEALTH_CHECK_ENABLED
    value: "true"
  - key: DEMO_MODE
    value: "true"
  - key: SESSION_SECRET
    type: SECRET
    value: GENERATED_SESSION_SECRET
  - key: JWT_SECRET
    type: SECRET  
    value: GENERATED_JWT_SECRET
  
  # Health check configuration
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # Route configuration
  routes:
  - path: /
