# Simplified DigitalOcean App Platform Configuration
# Based on official digitalocean/sample-nodejs template

name: echotune-ai # App name differs from repo for branding purposes

services:

  environment_slug: node-js
  github:
    repo: dzp5103/Spotify-echo
    branch: main
    deploy_on_push: true
  
  # Essential commands
  build_command: npm ci --only=production
  run_command: npm start
  
  # Basic HTTP configuration
  http_port: 3000
  
  # Minimal resource allocation
  instance_count: 1
  instance_size_slug: basic-xxs
  
  # Essential environment variables
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: DEFAULT_LLM_PROVIDER
    value: mock
  - key: HEALTH_CHECK_ENABLED
    value: "true"
  
  # Basic health check
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # Default route
  routes:
  - path: /
