name: echotune-ai
services:
- name: web
  source_dir: /
  github:
    repo: dzp5103/Spotify-echo
    branch: main
  run_command: npm start
  build_command: npm install --production
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: SPOTIFY_CLIENT_ID
    value: ${SPOTIFY_CLIENT_ID}
  - key: SPOTIFY_CLIENT_SECRET
    value: ${SPOTIFY_CLIENT_SECRET}
    type: SECRET
  - key: SPOTIFY_REDIRECT_URI
    value: https://echotune-ai-YOUR_APP_ID.ondigitalocean.app/auth/callback
  - key: SESSION_SECRET
    value: ${SESSION_SECRET}
    type: SECRET
  - key: JWT_SECRET
    value: ${JWT_SECRET}
    type: SECRET
