metadata:
  version: "5.0"
  last_updated: "2024-12-27T12:00:00Z"
  registry_maintainer: "EchoTune AI"
  description: "Comprehensive MCP server registry for EchoTune AI ecosystem"
  documentation: "https://github.com/dzp5103/Spotify-echo/docs/MCP_INTEGRATION.md"
  health_check_enabled: true
  auto_discovery: true
  
servers:
  - name: "filesystem-mcp-server"
    version: "1.2.0"
    type: "core"
    status: "active"
    description: "Enhanced filesystem operations with advanced file management"
    repository_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem"
    health_check_url: "http://localhost:3001/health/filesystem"
    capabilities:
      - "file_operations"
      - "directory_management"
      - "permission_control"
      - "file_search"
      - "content_analysis"
    configuration:
      allowed_paths:
        - "/home/runner/work/Spotify-echo/Spotify-echo"
        - "/tmp"
      max_file_size: "10MB"
      permissions: "read_write"
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "Model Context Protocol Team"
    tags: ["core", "filesystem", "enhanced"]
    
  - name: "package-management-mcp"
    version: "2.1.0"
    type: "automation"
    status: "active"
    description: "Automated package version management with security scanning"
    repository_url: "https://github.com/sammcj/mcp-package-version"
    health_check_url: "http://localhost:3001/health/package-mgmt"
    capabilities:
      - "version_checking"
      - "security_scanning"
      - "dependency_updates"
      - "vulnerability_analysis"
      - "compliance_reporting"
    configuration:
      package_managers:
        - "npm"
        - "pip"
        - "yarn"
      security_threshold: "medium"
      auto_update: false
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "sammcj"
    tags: ["automation", "security", "package-management"]
    
  - name: "code-sandbox-mcp"
    version: "1.5.2"
    type: "execution"
    status: "active"
    description: "Secure code execution environment with Deno runtime"
    repository_url: "https://github.com/bewt85/mcp-deno-sandbox"
    health_check_url: "http://localhost:3001/health/sandbox"
    capabilities:
      - "code_execution"
      - "typescript_support"
      - "javascript_support"
      - "isolated_environment"
      - "permission_controls"
    configuration:
      runtime: "deno"
      timeout: 30000
      memory_limit: "128MB"
      network_access: false
      file_system_access: "restricted"
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "bewt85"
    tags: ["execution", "sandbox", "security", "deno"]
    
  - name: "analytics-telemetry-mcp"
    version: "3.0.1"
    type: "monitoring"
    status: "active"
    description: "Advanced analytics and telemetry with OpenTelemetry integration"
    repository_url: "https://github.com/shinzo-labs/shinzo-ts"
    health_check_url: "http://localhost:3001/health/analytics"
    capabilities:
      - "performance_monitoring"
      - "user_analytics"
      - "system_telemetry"
      - "real_time_insights"
      - "custom_metrics"
    configuration:
      metrics_endpoint: "http://localhost:4317"
      sampling_rate: 0.1
      batch_size: 100
      export_interval: 5000
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "Shinzo Labs"
    tags: ["monitoring", "analytics", "telemetry", "opentelemetry"]
    
  - name: "browser-automation-mcp"
    version: "2.3.0"
    type: "automation"
    status: "active"
    description: "Enhanced browser automation for Spotify Web Player integration"
    repository_url: "https://github.com/playcanvas/editor-mcp-server"
    health_check_url: "http://localhost:3001/health/browser"
    capabilities:
      - "web_automation"
      - "spotify_integration"
      - "ui_testing"
      - "visual_regression"
      - "performance_monitoring"
    configuration:
      browser: "chromium"
      headless: true
      timeout: 30000
      spotify_integration: true
      screenshot_enabled: true
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "PlayCanvas"
    tags: ["automation", "browser", "spotify", "testing"]
    
  - name: "database-connector-mcp"
    version: "1.8.0"
    type: "data"
    status: "active"
    description: "Multi-database connector with MongoDB and PostgreSQL support"
    repository_url: "https://github.com/echotune-ai/database-mcp-server"
    health_check_url: "http://localhost:3001/health/database"
    capabilities:
      - "mongodb_operations"
      - "postgresql_operations"
      - "query_optimization"
      - "connection_pooling"
      - "transaction_management"
    configuration:
      mongodb_uri: "${MONGODB_URI}"
      postgresql_uri: "${DATABASE_URL}"
      pool_size: 10
      timeout: 5000
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "EchoTune AI"
    tags: ["database", "mongodb", "postgresql", "data"]
    
  - name: "llm-integration-mcp"
    version: "2.5.0"
    type: "ai"
    status: "active"
    description: "Multi-provider LLM integration with OpenAI, Gemini, and Claude support"
    repository_url: "https://github.com/echotune-ai/llm-mcp-server"
    health_check_url: "http://localhost:3001/health/llm"
    capabilities:
      - "openai_integration"
      - "google_gemini"
      - "anthropic_claude"
      - "model_switching"
      - "conversation_memory"
    configuration:
      default_provider: "openai"
      fallback_enabled: true
      context_window: 4096
      temperature: 0.7
      max_tokens: 2048
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "EchoTune AI"
    tags: ["ai", "llm", "openai", "gemini", "claude"]
    
  - name: "music-analysis-mcp"
    version: "1.4.0"
    type: "specialized"
    status: "active"
    description: "Specialized music analysis with Spotify API integration"
    repository_url: "https://github.com/echotune-ai/music-analysis-mcp"
    health_check_url: "http://localhost:3001/health/music"
    capabilities:
      - "audio_feature_analysis"
      - "spotify_api_integration"
      - "playlist_management"
      - "music_recommendation"
      - "genre_classification"
    configuration:
      spotify_client_id: "${SPOTIFY_CLIENT_ID}"
      spotify_client_secret: "${SPOTIFY_CLIENT_SECRET}"
      analysis_cache_ttl: 3600
      feature_extraction: true
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "EchoTune AI"
    tags: ["music", "spotify", "analysis", "recommendation"]
    
  - name: "cache-management-mcp"
    version: "1.6.0"
    type: "infrastructure"
    status: "active"
    description: "Distributed cache management with Redis and memory caching"
    repository_url: "https://github.com/echotune-ai/cache-mcp-server"
    health_check_url: "http://localhost:3001/health/cache"
    capabilities:
      - "redis_operations"
      - "memory_caching"
      - "cache_invalidation"
      - "distributed_locking"
      - "performance_metrics"
    configuration:
      redis_url: "${REDIS_URL}"
      memory_limit: "256MB"
      default_ttl: 3600
      compression: true
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "EchoTune AI"
    tags: ["cache", "redis", "performance", "infrastructure"]
    
  - name: "notification-service-mcp"
    version: "1.3.0"
    type: "communication"
    status: "active"
    description: "Multi-channel notification service with email, SMS, and webhook support"
    repository_url: "https://github.com/echotune-ai/notification-mcp-server"
    health_check_url: "http://localhost:3001/health/notifications"
    capabilities:
      - "email_notifications"
      - "sms_notifications"
      - "webhook_delivery"
      - "template_management"
      - "delivery_tracking"
    configuration:
      email_provider: "sendgrid"
      sms_provider: "twilio"
      rate_limiting: true
      retry_attempts: 3
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "EchoTune AI"
    tags: ["notifications", "communication", "email", "sms"]
    
  - name: "workflow-orchestrator-mcp"
    version: "2.0.0"
    type: "orchestration"
    status: "active"
    description: "Advanced workflow orchestration and task coordination"
    repository_url: "https://github.com/echotune-ai/workflow-mcp-server"
    health_check_url: "http://localhost:3001/health/workflow"
    capabilities:
      - "workflow_definition"
      - "task_scheduling"
      - "parallel_execution"
      - "error_handling"
      - "state_management"
    configuration:
      max_concurrent_workflows: 10
      task_timeout: 300000
      retry_policy: "exponential_backoff"
      state_persistence: true
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "EchoTune AI"
    tags: ["orchestration", "workflow", "scheduling", "automation"]
    
  - name: "security-scanner-mcp"
    version: "1.7.0"
    type: "security"
    status: "active"
    description: "Comprehensive security scanning with vulnerability detection"
    repository_url: "https://github.com/echotune-ai/security-scanner-mcp"
    health_check_url: "http://localhost:3001/health/security"
    capabilities:
      - "vulnerability_scanning"
      - "dependency_auditing"
      - "secret_detection"
      - "compliance_checking"
      - "risk_assessment"
    configuration:
      scan_depth: "deep"
      update_frequency: "daily"
      cvss_threshold: 7.0
      include_dev_dependencies: true
    last_updated: "2024-12-27T12:00:00Z"
    maintainer: "EchoTune AI"
    tags: ["security", "vulnerability", "compliance", "scanning"]

statistics:
  total_servers: 12
  active_servers: 12
  deprecated_servers: 0
  server_types:
    core: 1
    automation: 3
    execution: 1
    monitoring: 1
    data: 1
    ai: 1
    specialized: 1
    infrastructure: 1
    communication: 1
    orchestration: 1
    security: 1
  
health:
  overall_score: 95
  last_health_check: "2024-12-27T12:00:00Z"
  healthy_servers: 12
  unhealthy_servers: 0
  average_response_time: "45ms"
  
configuration:
  health_check_interval: 300
  auto_discovery_enabled: true
  performance_monitoring: true
  security_scanning: true
  compliance_validation: true