name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Deploy App spec
        run: |
          doctl apps create --spec .do/apps.yml
          # or doctl apps update ${{ steps.create.outputs.app_id }} --spec .do/apps.yml
