            - name: Gemini AI Code Reviewer
  # You may pin to the exact commit or the version.
  # uses: truongnh1992/gemini-ai-code-reviewer@af1034dd2f6616858a9c8540bb5460f1f3f28b1d
  uses: truongnh1992/gemini-ai-code-reviewer@v6.5.0
  with:
    # GitHub token to interact with the repository
    GITHUB_TOKEN: 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
    # Google Gemini API key
    GEMINI_API_KEY: AIzaSyCWu_GO1r-oX-ujaglXSmXi_pvIegO46U0
    # The Gemini model to use for code review
    GEMINI_MODEL: gemini-2.5-flash-lite # optional, default is gemini-1.5-flash-002
    # Comma-separated list of file patterns to exclude
    INPUT_EXCLUDE: # optional, default is 
          
