name: MCP Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  repository_dispatch:
    types: [mcp-health-check, run-mcp-validation]

jobs:
  mcp-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install root deps (if present)
        run: |
          if [ -f package.json ]; then npm ci || true; fi
      - name: MCP install
        run: node scripts/mcp-manager.js install
      - name: MCP health
        run: node scripts/mcp-manager.js health
      - name: MCP test
        run: node scripts/mcp-manager.js test
      - name: MCP report
        run: node scripts/mcp-manager.js report
      - name: Upload MCP logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mcp-logs
          path: |
            mcp-server/*.log
            mcp-server/**/*.log
            **/mcp-report*.txt