name: MCP — Validation Suite

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  run-mcp:
    if: |
      github.event_name == 'workflow_dispatch' || contains(github.event.comment.body, '/run-mcp-all') || contains(github.event.comment.body, '/run-mcp-validation') || contains(github.event.comment.body, '/mcp-discover') || contains(github.event.comment.body, '/mcp-health-check')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare workspace
        run: |
          mkdir -p reports mcp scripts/mcp

      - name: Run MCP placeholder validations
        run: |
          bash scripts/mcp/run.sh

      - name: Upload MCP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-validation
          path: |
            reports/mcp-health.md
            mcp/registry.yaml
          if-no-files-found: warn