name: Redundancy Audit
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  redundancy-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install jscpd
        run: npm i -g jscpd@4
      - name: Run jscpd
        run: |
          mkdir -p reports
          jscpd --reporters markdown --output reports || true
          if [ -f reports/jscpd-report.md ]; then
            mv reports/jscpd-report.md reports/redundancy-audit.md
          else
            echo "# Redundancy Audit\n\nNo report generated." > reports/redundancy-audit.md
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: redundancy-audit
          path: reports/redundancy-audit.md